config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes, only: [:new, :show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end

  get 'tag_index',to: 'recipes#tag_index'

  get 'search' => 'recipes#search' #ソート機能

  get 'all_search' => 'searchs#all_search' #検索機能

  resources :tags do
    get 'recipes', to: 'recipes#tag_search'  #タグ一覧先
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  attachment :image
  has_many :recipe_ingredients, dependent: :destroy
  has_many :how_to_makes, dependent: :destroy
  accepts_nested_attributes_for :recipe_ingredients, :how_to_makes, allow_destroy: true
  validates :title, length: { minimum: 2, maximum: 20 }, presence: true
  validates :catchcopy, presence: true, length: { maximum: 200 }

  has_many :favorites, dependent: :destroy

  has_many :recipe_comments, dependent: :destroy

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  validates :sweetness, :spicy, :salty, :bitter_taste, :acidity, presence: true


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def user
    return User.find_by(id: self.user_id)
  end

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'likes'
      return find(Favorite.group(:recipe_id).order(Arel.sql('count(recipe_id) desc')).pluck(:recipe_id))
    when 'dislikes'
      return find(Favorite.group(:recipe_id).order(Arel.sql('count(recipe_id) asc')).pluck(:recipe_id))
    end
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old_name|
      self.recipet_tags.delete Tag.find_by(tag_name: old_name)
    end
    new_tags.each do |new_name|
      recipe_tag = Tag.find_or_create_by(tag_name: new_name)
      self.tags << recipe_tag
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update, :destroy]
 before_action :authenticate_user!, only: [:new, :show]

  def new
    @recipe = Recipe.new
    @recipe_ingredients = @recipe.recipe_ingredients.build #buildで子モデルのインスタンスを作成
    @how_to_makes = @recipe.how_to_makes.build
  end

  def show
    @user = current_user
    @recipe = Recipe.find(params[:id])
    @recipe_ingredients = @recipe.recipe_ingredients.all #追加分の子モデルを表示するため
    @how_to_makes = @recipe.how_to_makes.all
    @recipe_comment = RecipeComment.new
    @recipe_tags = @recipe.tags         #そのクリックした投稿に紐付けられているタグの取得。
  end

  def index
    @recipes = Recipe.all
    @user = current_user
    @recipes = Recipe.page(params[:page]).reverse_order
  end
  
  def tag_index
     @tag_list = Tag.all              #ビューでタグ一覧を表示するために全取得。
     @tag_list = Tag.page(params[:page]).reverse_order
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    tag_list = params[:recipe][:tag_name].split(nil)
    if @recipe.save
       @recipe.save_tag(tag_list)
      redirect_to recipe_path(@recipe)
    else
      render new_recipe_path
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
   if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id)
   else
      render 'edit'
   end
  end


  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe_ingredients = @recipe.recipe_ingredients.all
    @how_to_makes = @recipe.how_to_makes.all
    @recipe.destroy
    redirect_to recipes_path
  end

  def search
    selection = params[:keyword]
    @recipes = Recipe.sort(selection)
  end

  def tag_search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @recipes = @tag.recipes.all
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :catchcopy, :no_of_dish, :image, :sweetness, :spicy, :salty, :bitter_taste, :acidity,
                                  recipe_ingredients_attributes:[:ing_name, :quantity, :_destroy, :id],
                                  how_to_makes_attributes:[:explanation, :_destroy, :id])
  end


#他のユーザーが編集できないように
  def ensure_correct_user
    @recipe = Recipe.find(params[:id])
    unless @recipe.user == current_user
      redirect_to recipes_path
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_how_to_make_fields.html.erb
<!--動的フォーム-->
<div class="nested-fields">
  <div class="container">
   <label for="Procedure">手順</label>
    <div><%= f.text_area :explanation, placeholder: "手順", class: "form-control mb-3" %></div>
    <div class="delete-btn"><%= link_to_remove_association "↑削除する", f, class: "badge badge-pill badge-warning text-white mt-2 ml-2" %></div>
  </div>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<!--動的フォーム-->
<div class="nested-fields">
  <div class="container">
   <div class="row">
     <div class="col-md-6 mb-3">
       <label for="Material">材料</label>
       <div><%= f.text_field :ing_name, placeholder: "材料", class: "form-control" %></div>
     </div>
     <div class="col-md-6 mb-3">
       <label for="Quantity">分量</label>
        <div><%= f.text_field :quantity, placeholder: "分量", class: "form-control" %></div>
     </div>
    </div>
    <div class="delete-btn">
      <%= link_to_remove_association "↑削除する", f, class: "badge badge-pill badge-warning text-white m-2" %>
    </div>
  </div>
</div>

app/views/recipes/_result.html.erb
<!--レシピ表示-->
<% @recipes.each do |recipe| %>
  <div class="card mb-5 w-75  mx-auto shadow-lg">
    <div class="row">
     <div class="col-lg-5-md-6-sm-6">
       <div class="img-container"><%= attachment_image_tag recipe, :image, :fill, 300, 300, fallback: "pngtree.jpg", size:'300x300' %></div>
     </div>
     <div class="col-lg-7-md-6-sm-6">
       <div class="card-body">
         <p class="card-text ml-5">
           <%= attachment_image_tag recipe.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class:"mt-4 mr-3 rounded-circle" %>
           by. <%= recipe.user.name %>
         </p>
         <h5 class="card-title ml-5">料理名★<%= link_to recipe_path(recipe.id), class:"font-color" do %>
           <%= recipe.title %>
           <% end %>
         </h5>
         <div class="catchcopy ml-5"><%= recipe.catchcopy %></div>
       </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_select_form.html.erb
<!--ソートバー-->
<%= form_with model: @recipe, url: search_path, method: :get, local: true do |form| %>
 <div class="text-left ml-5 mt" >
   <div class="form-row ">
     <div class="col-sm-7">
       <%= form.select :keyword, [ ['投稿が新しい順', 'new'],
                                ['投稿が古い順', 'old'],
                                ['いいねが多い順', 'likes'],
                                ['いいねが少ない順', 'dislikes']], {}, {:class => "form-control"}  %>
     </div>
     <div class="col">
       <button type="form.submit" class="btn btn-outline-warning">変更</button>
     </div>
   </div>
 </div>
<% end %>

app/views/recipes/_show_star.html.erb
<div class="card-group">
  <div class="card border-0">
    <div class="card-body">
      <div class="card-title">
        <div class="star-group">
         <div class="detail-review">甘味</div>
         <div class="detail-value", id="star1-<%= recipe.id %>"></div>
        </div>
      </div>
      <div class="card-text">
       <script>
         $('#star1-<%=recipe.id %>').raty({
          size: 36,
          starOff: "<%= asset_path('star-off.png') %>",
          starOn: "<%= asset_path('star-on.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          half: true,
          readOnly: true,
          score: <%= recipe.sweetness %>,
         });
       </script>
      </div>
    </div>
  </div>
  <div class="card border-0">
    <div class="card-body">
      <div class="card-title">
        <div class="star-group">
        <div class="detail-review">辛味</div>
        <div class="detail-value", id="star2-<%= recipe.id %>"></div>
        </div>
      </div>
      <div class="card-text">
      <script>
        $('#star2-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.spicy %>,
        });
      </script>
      </div>
    </div>
  </div>
   <div class="card border-0">
    <div class="card-body">
      <div class="card-title">
      <div class="star-group">
      <div class="detail-review">塩味</div>
       <div class="detail-value", id="star3-<%= recipe.id %>"></div>
      </div>
      </div>
      <div class="card-text">
      <script>
        $('#star3-<%= recipe.id %>').raty({
          size: 36,
          starOff: "<%= asset_path('star-off.png') %>",
          starOn: "<%= asset_path('star-on.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          half: true,
          readOnly: true,
          score: <%= recipe.salty %>,
        });
     </script>
      </div>
    </div>
  </div>
  <div class="card border-0">
    <div class="card-body">
      <div class="card-title">
       <div class="star-group">
        <div class="detail-review">苦味</div>
        <div class="detail-value", id="star4-<%= recipe.id %>"></div>
      </div>
      </div>
      <div class="card-text">
        <script>
       $('#star4-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.bitter_taste %>,
        });
      </script>
      </div>
    </div>
  </div>
    <div class="card border-0">
    <div class="card-body">
      <div class="card-title">
       <div class="star-group">
        <div class="detail-review">酸味</div>
        <div class="detail-value", id="star5-<%= recipe.id %>"></div>
     </div>
      </div>
      <div class="card-text">
      <script>
       $('#star5-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.acidity %>,
        });
       </script>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_star.html.erb
<div>
    <div>
      <div class="star-group">
        <div class="detail-review">甘</div>
        <div class="detail-value", id="star1-<%= recipe.id %>"></div>
     </div>
     <script>
       $('#star1-<%=recipe.id %>').raty({
        size: 36,
        starOff: "<%= asset_path('star-off.png') %>",
        starOn: "<%= asset_path('star-on.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        half: true,
        readOnly: true,
        score: <%= recipe.sweetness %>,
       });
     </script>
     <%= recipe.sweetness %>
    </div>

    <div>
     <div class="star-group">
        <div class="detail-review">辛</div>
        <div class="detail-value", id="star2-<%= recipe.id %>"></div>
     </div>
     <script>
        $('#star2-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.spicy %>,
        });
     </script>
      <%= recipe.spicy %>
   </div>

   <div>
     <div class="star-group">
       <div class="detail-review">塩</div>
       <div class="detail-value", id="star3-<%= recipe.id %>"></div>
      </div>
      <script>
        $('#star3-<%= recipe.id %>').raty({
          size: 36,
          starOff: "<%= asset_path('star-off.png') %>",
          starOn: "<%= asset_path('star-on.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          half: true,
          readOnly: true,
          score: <%= recipe.salty %>,
        });
     </script>
      <%= recipe.salty %>
   </div>

   <div>
      <div class="star-group">
        <div class="detail-review">渋</div>
        <div class="detail-value", id="star4-<%= recipe.id %>"></div>
      </div>
      <script>
       $('#star4-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.bitter_taste %>,
        });
      </script>
      <%= recipe.bitter_taste %>
   </div>

   <div>
     <div class="star-group">
        <div class="detail-review">酸</div>
        <div class="detail-value", id="star5-<%= recipe.id %>"></div>
     </div>
     <script>
       $('#star5-<%= recipe.id %>').raty({
         size: 36,
         starOff: "<%= asset_path('star-off.png') %>",
         starOn: "<%= asset_path('star-on.png') %>",
         starHalf: "<%= asset_path('star-half.png') %>",
         half: true,
         readOnly: true,
         score: <%= recipe.acidity %>,
        });
     </script>
      <%= recipe.acidity %>
   </div>
</div>

app/views/recipes/edit.html.erb
 <!--エラーメッセージ-->
<% if @recipe.errors.any? %>
 <h2 class="errors text-center mb-5"><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
<% end %>

 <!--投稿画面-->
  <%= form_with model: @recipe, local:true do |f| %>
   <div class="container w-75 mt-5">
      <h2 class="far fa-clipboard">WriteRecipe</h2>
      <div class="my-3 ">
       <label for="RecipeTitle" class="tag_text">レシピタイトル</label>
       <div><%= f.text_field :title, placeholder: "レシピタイトル", class: "form-control js-text-top" %></div>
       <P class="js-text-top-count pull-right"></P>
       <% if @recipe.errors.include?(:title) %>
         <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:title).first %>
       <% end %>
      </div>

       <div class="row">
         <div class="col-md-6 mb-3">
           <label for="NumberOfPeople" class="tag_text">人数</label>
              <div><%= f.text_field :no_of_dish, placeholder: "２人分", class: "form-control" %></div>
        </div>
           <div class="col-md-6 mb-3">
             <label for="Tag" class="tag_text">タグ</label>
                <div>
                 <%= f.text_field :tag_name,placeholder: "料理に合うお酒の名前を記入してください", class: "form-control" %>
                </div>
            </div>
        </div>

       <div class="mb-3">
          <label for="CatchCopy" class="tag_text">キャッチコピー</label>
          <div><%= f.text_area :catchcopy, placeholder: "キャッチコピー入力（検索結果の画面にも表示されます）", class: "form-control js-text" %></div>
          <P class="js-text-count pull-right"></P>
        </div>
        <% if @recipe.errors.include?(:catchcopy) %>
         <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:catchcopy).first %>
        <% end %>

       <div class="mb-3">
          <label for="Image" class="tag_text">イメージ</label>
          <div><%= f.attachment_field :image %></div>
        </div>


        <div class="star-form-group" id="star1-<%= @recipe.id %>">
          <%= f.label :sweetness,'甘味', class:'star-title tag_text' %>
          <script>
           $('#star1-<%= @recipe.id %>').raty({
             size     : 36,
             starOff:  '<%= asset_path('star-off.png') %>',
             starOn : '<%= asset_path('star-on.png') %>',
             starHalf: '<%= asset_path('star-half.png') %>',
             score: <%= @recipe.sweetness %>,
             scoreName: 'recipe[sweetness]',
             half: true,
           });
         </script>
        </div>

        <div class="star-form-group" id="star2-<%= @recipe.id %>">
          <%= f.label :spicy,'辛味', class:'star-title tag_text' %>
         <script>
           $('#star2-<%= @recipe.id %>').raty({
             size     : 36,
             starOff:  '<%= asset_path('star-off.png') %>',
             starOn : '<%= asset_path('star-on.png') %>',
             starHalf: '<%= asset_path('star-half.png') %>',
             score: <%= @recipe.spicy %>,
             scoreName: 'recipe[spicy]',
             half: true,
           });
         </script>
        </div>

        <div class="star-form-group" id="star3-<%= @recipe.id %>">
          <%= f.label :salty,'塩味', class:'star-title tag_text' %>
          <script>
           $('#star3-<%= @recipe.id %>').raty({
             size     : 36,
             starOff:  '<%= asset_path('star-off.png') %>',
             starOn : '<%= asset_path('star-on.png') %>',
             starHalf: '<%= asset_path('star-half.png') %>',
             score: <%= @recipe.salty %>,
             scoreName: 'recipe[salty]',
             half: true,
            });
         </script>
        </div>

        <div class="star-form-group" id="star4-<%= @recipe.id %>">
          <%= f.label :bitter_taste,'苦味', class:'star-title tag_text' %>
          <script>
           $('#star4-<%= @recipe.id %>').raty({
             size     : 36,
             starOff:  '<%= asset_path('star-off.png') %>',
             starOn : '<%= asset_path('star-on.png') %>',
             starHalf: '<%= asset_path('star-half.png') %>',
             score: <%= @recipe.bitter_taste %>,
             scoreName: 'recipe[bitter_taste]',
             half: true,
           });
         </script>
        </div>

        <div class="star-form-group" id="star5-<%= @recipe.id %>">
          <%= f.label :acidity,'酸味', class:'star-title tag_text' %>
          <script>
           $('#star5-<%= @recipe.id %>').raty({
             size     : 36,
             starOff:  '<%= asset_path('star-off.png') %>',
             starOn : '<%= asset_path('star-on.png') %>',
             starHalf: '<%= asset_path('star-half.png') %>',
             score: <%= @recipe.acidity %>,
             scoreName: 'recipe[acidity]',
             half: true,
           });
         </script>
        </div>


        <!--星評価のエラー分-->
        <% if @recipe.errors.include?(:sweetness) %>
          <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:sweetness).first %>
        <% end %>
        <% if @recipe.errors.include?(:spicy) %>
          <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:spicy).first %>
        <% end %>
        <% if @recipe.errors.include?(:salty,) %>
          <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:salty).first %>
        <% end %>
        <% if @recipe.errors.include?(:bitter_taste) %>
          <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:bitter_taste).first %>
        <% end %>
        <% if @recipe.errors.include?(:acidity) %>
          <p style="color: white; background-color: red;"><%= @recipe.errors.full_messages_for(:acidity).first %>
        <% end %>

         <!--材料・量の入力フォーム-->
         <div class="recipe-ingredients">
           <div>
            <%= f.fields_for :recipe_ingredients do |t| %>
              <%= render "recipes/recipe_ingredient_fields", f: t %>
            <% end %>
          </div>
          <div>
            <%= link_to_add_association "+フォームを追加", f, :recipe_ingredients, class: "btn btn-outline-warning w-100" %>
          </div>
        </div>

        <!--手順の入力フォーム-->
        <div class="how-to-makes">
          <div>
            <%= f.fields_for :how_to_makes do |t| %>
              <%= render "recipes/how_to_make_fields", f: t %>
            <% end %>
          </div>
          <div>
            <%= link_to_add_association "+フォームを追加", f, :how_to_makes, class: "btn btn-outline-warning w-100 mt-2" %>
          </div>
        </div>

    <div class="text-center">
     <button type="submit" class="btn btn-warning w-75 my-5 ml-2">保存</button>
   </div>
 </div>
<% end %>

app/views/recipes/index.html.erb
<div class="my-4 searchs">
 <%= render 'searchs/form' %>
</div>

<%= render 'result', recipe: @recipe %>
<%= paginate @recipes %>

app/views/recipes/search.html.erb
<!--ソート一覧ページ-->

<div class="mb-3 searchs">
  <%= render 'select_form' %>
</div>

<%= render 'result', recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="container mt-5">
   <div class="text-center">
      <div class="d-block mx-auto mb-4"><%= attachment_image_tag @recipe, :image,:fill, 600, 600, fallback: "pngtree.jpg", class:"mt-3 mr-3 rounded-circle"%></div>
      <h3><%= @recipe.title %></h3>
      <div class="mt-4"><%= link_to user_path(@user.id) do %>
          <div><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50', class:" rounded-circle" %></div>
          <p class="link-color">by.<%= @user.name %></p>
           <% end %>
      </div>
      <% if user_signed_in? && current_user.id == @recipe.user_id %>
       <P class="link-color"><%= link_to "Edit", edit_recipe_path(@recipe), data: {"turbolinks" => false} %> / <%= link_to "Destroy", recipe_path(@recipe), method: :delete, data: { confirm: '本当に消しますか？' }, "dete-confirm" =>"Are you sure?" %></P>
     <% end %>

     <div class="card text-center w-75 mx-auto border-0">
        <div class="card-body">
         <h5 class="card-title">- - - - - -Cooking Description- - - - - -</h5>
         <p class="card-text"><%= @recipe.catchcopy %></p>
         <div id="favorite-btn_<%= @recipe.id %>">
            <%= render partial: 'favorites/favorite-btn', locals: { recipe: @recipe} %>
         </div>
        </div>
     </div>
    </div>

    <!--☆評価-->
    <div><%= render 'recipes/show_star', recipe: @recipe %></div>

     <div class="my-3">
      <p>【人数分】<%= @recipe.no_of_dish %></p>
      <table class="table">
          <thead>
           <tr class="table-warning">
             <th>食材</th>
             <th>分量</th>
           </tr>
         </thead>
        <tbody>
        <% @recipe_ingredients.each do |t| %>
          <tr>
            <td><%= t.ing_name %></td>
            <td><%= t.quantity %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div>
       <table class="table">
          <thead>
           <tr class="table-warning">
             <th>手順</th>
           </tr>
         </thead>
        <tbody>
        <% @how_to_makes.each do |t| %>
          <tr>
            <td><%= t.explanation %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
     </div>

   <!--コメント-->
    <table class="recipe_comments table">
      <%= render 'recipe_comments/index', recipe: @recipe,recipe_comment: @recipe_comment%>
    </table>

    <div class="w-75 mx-auto mt-5">
      <%= form_with model:[@recipe,@recipe_comment] do |f| %>
       <%= f.text_area :comment, placeholder: "コメント入力フォーム", size:"90x5", class: "form-control" %>
       <p>(150文字)</p>
      <div class="text-center">
       <button type="submit" class="btn btn-outline-warning w-75 my-3">コメントを送る</button>
      </div>
      <% end %>
    </div>

  </div>

app/views/recipes/tag_index.html.erb
<!--searchページ-->
<div>
  <div class="mt-5">
   <%= render 'select_form' %>
  </div>
  <div>
   <%= render 'searchs/form' %>
  </div>
  <h3 class="ml-5 mt-2"><i class="fas fa-tags"></i> タグリスト</h3>
   <% @tag_list.each do |list| %>
     <p class="text-center tag-color m-5"><%= link_to list.tag_name, tag_recipes_path(tag_id: list.id), class: "tag-text" %><%= "(#{list.recipes.count})" %></p>
   <% end %>

   <%= paginate @tag_list %>

</div>

app/views/recipes/tag_search.html.erb
<!--タグのついたレシピ一覧-->
<%= render 'result', recipe: @recipe %>