config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes, only: [:new, :show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end

  get 'tag_index',to: 'recipes#tag_index'

  get 'search' => 'recipes#search' #ソート機能

  get 'all_search' => 'searchs#all_search' #検索機能

  resources :tags do
    get 'recipes', to: 'recipes#tag_search'  #タグ一覧先
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  validates :name, length: { maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 150 }
  has_many :recipes, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_many :recipe_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed



  def recipes
   return Recipe.where(user_id: self.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update]
 before_action :authenticate_user!, except: [:index]


  def show
    @user = User.find(params[:id])
  end
  
  def index
    redirect_to new_user_registration_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

#他のユーザーが編集
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<!--フォロー・フォロワー-->
<dv>
  <div class="m-2">follows
   <%= link_to user_followings_path(user), class:"font-color" do %>
    <%= user.followings.count %>
   <% end %>
   followers
   <%= link_to user_followers_path(user), class:"font-color" do %>
    <%= user.followers.count %>
   <% end %>
  </div>

  <div class="mb-3">
   <% unless current_user == user %>
    <% if current_user.following?(user) %>
     <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn btn-outline-info" %>
    <% else %>
     <%= link_to "フォローをする", user_relationships_path(user.id), method: :post, class:"btn btn-outline-warning" %>
    <% end %>
   <% end %>
  </div>
</dv>

app/views/users/edit.html.erb
<!--プロフィール編集-->
<div class="container m-5">
  <div class="row">
    <div class="col-lo-8sm-7">
      <h3>プロフィール編集</h3>
       <%= form_with model:@user, local:true do |f| %>
        <label for="inputName">Name</label>
          <div class="mb-2"><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control js-text-top"%></div>
          <P class="js-text-top-count pull-right"></P>
          <div><%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg", class: "rounded-circle" %></div>
        <label for="inputImage">プロフィール画像</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <div><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction", class: "form-control input-lg js-text" %></div>
          <P class="js-text-count pull-right"></P>
        </div>
        <div class="text-center">
         <button type="submit" class="btn btn-warning w-75 my-5 ml-2">保存</button>
        </div>
        </div>
        <% end %>
     </div>
  </div>
</div>

app/views/users/show.html.erb
<!--プロフィール-->
 <div class="text-center my-5">
   <div class="d-block mx-auto mb-4"> <%= attachment_image_tag @user, :profile_image, :fill, 130, 130, format: 'jpeg', fallback: "no_image.jpg", class:"mt-3 mr-3 rounded-circle"%></div>
     <h3><%= @user.name %></h3>
     <p><%= render 'users/info', user: @user %></p>
     <p class="lead">- - - - - -introduction- - - - - -</p>
     <div class="profile w-75 mx-auto">
       <div class =" m-3">
         <%= @user.introduction %>
       </div>
     </div>
     <% if @user.id == current_user.id %>
       <p class="mt-3"><%= link_to edit_user_path(@user),data: {"turbolinks" => false}, class:"font-color" do %>
         <i class="fas fa-user-edit"></i>
         <% end %>
       </p>
     <% end %>
 </div>


<!--My投稿一覧-->
<% @user.recipes.each do |recipe| %>
 <div class="card mb-5 w-75  mx-auto shadow-lg">
   <div class="row">
     <div class="col-lg-5-md-6-sm-6">
       <div class="img-container"><%= attachment_image_tag recipe, :image, :fill, 300, 300, fallback: "pngtree.jpg", size:'300x300' %></div>
     </div>
     <div class="col-lg-7-md-6-sm-6">
       <div class="card-body">
         <h5 class="card-title ml-5">料理名：<%= link_to recipe_path(recipe.id), class:"font-color" do %>
            <%= recipe.title %>
           <% end %>
         </h5>
         <div class="card-text ml-5">人数分：<%= recipe.no_of_dish %></div>
         <div class="text ml-5 mt-2"><%= recipe.catchcopy %></div>
       </div>
     </div>
   </div>
 </div>
<% end %>