config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes, only: [:new, :show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end

  get 'tag_index',to: 'recipes#tag_index'

  get 'search' => 'recipes#search' #ソート機能

  get 'all_search' => 'searchs#all_search' #検索機能

  resources :tags do
    get 'recipes', to: 'recipes#tag_search'  #タグ一覧先
  end
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :comment, length: { maximum: 150 }, presence: true
end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController

	def create
		@recipe = Recipe.find(params[:recipe_id])
		@recipe_comment = RecipeComment.new(recipe_comment_params)
		@recipe_comment.recipe_id = @recipe.id
		@recipe_comment.user_id = current_user.id
		unless @recipe_comment.save
		  render 'recipes/show'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:recipe_id])
  	recipe_comment = @recipe.recipe_comments.find(params[:id])
		recipe_comment.destroy
	end

	private
	def recipe_comment_params
		params.require(:recipe_comment).permit(:comment)
	end
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/views/recipe_comments/_index.html.erb
<% recipe.recipe_comments.each do |recipe_comment| %>
   <% recipe_comment_user = recipe_comment.user %>
    <tr>
      <td>
        <%= link_to user_path(recipe_comment_user), class: "user_#{recipe_comment_user.id}" do %>
        <%= attachment_image_tag recipe_comment_user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60", class:"rounded-circle mr-3" %></br>
        <p class="name-text"><%= recipe_comment_user.name %></p>
        <% end %>
      </td>

      <td><%= recipe_comment.comment %></br>
      	<% if current_user == recipe_comment_user %>
        <%= link_to '↑削除する', recipe_recipe_comment_path(recipe_comment.recipe_id, recipe_comment.id),method: :delete, remote: true, class: "badge badge-pill badge-warning text-white m-2 " %></td>
      	<% end %>
     </tr>
<% end %>

app/views/recipe_comments/create.js.erb
$(".recipe_comments").html("<%= j(render 'recipe_comments/index', recipe: @recipe) %>");
$("#recipe_comment_comment").val("");

app/views/recipe_comments/destroy.js.erb
$(".recipe_comments").html("<%= j(render 'recipe_comments/index', recipe: @recipe) %>");
$("#recipe_comment_comment").val("");

app/views/recipe_comments/error.js.erb
$(".body > .container").prepend("<%= j(render 'layouts/errors', obj: @recipe_comment) %>");