config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :recipes, only: [:new, :show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :recipe_comments, only: [:create, :destroy]
  end

  get 'tag_index',to: 'recipes#tag_index'

  get 'search' => 'recipes#search' #ソート機能

  get 'all_search' => 'searchs#all_search' #検索機能

  resources :tags do
    get 'recipes', to: 'recipes#tag_search'  #タグ一覧先
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def all_search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = all_search_for(@model, @content, @method)
  end

 private

  def match(model, content)
   if model == 'user'
     User.where(name: content)
   elsif model == 'recipe'
     Recipe.where(title: content)
   end
  end

   def forward(model, content)
     if model == 'user'
       User.where("name LIKE ?", "#{content}%")
     elsif model == 'recipe'
       Recipe.where("title LIKE ?", "#{content}%")
     end
   end

   def backward(model, content)
     if model == 'user'
       User.where("name LIKE ?", "%#{content}")
     elsif model == 'recipe'
       Recipe.where("title LIKE ?", "%#{content}")
     end
   end

   def partical(model, content)
     if model == 'user'
       User.where("name LIKE ?", "%#{content}%")
     elsif model == 'recipe'
       Recipe.where("title LIKE ?", "%#{content}%")
     end
   end

   def all_search_for(model, content, method)
     case method
     when 'match'
       match(model, content)
     when 'forward'
      forward(model, content)
     when 'backward'
       backward(model, content)
     when 'partical'
       partical(model, content)
     end
   end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/_form.html.erb
<!--検索バー-->

<% if user_signed_in? %>
  <%= form_tag(all_search_path, method: :get) do %>
    <div class="text-left ml-5 " >
      <div class="form-row">
        <div class="form-group col-sm-5">
          <%= text_field_tag 'content', params[:content], class: "form-control mb-2 mr-sm-2 my-2", placeholder: "ワードを入力して下さい" %>
        </div>
       <div class="form-group col-sm-2">
          <%= select_tag 'model', options_for_select({ "User" => "user", "Recipe" => "recipe" }), class:"custom-select mt-2"%>
       </div>
       <div class="form-group col-sm-2">
         <%= select_tag 'method', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }), class:"custom-select mt-2" %>
       </div>
       <div class="form-group col-sm-1">
         <%= submit_tag "検索", class:"mb-2 my-2 btn btn-outline-warning" %>
       </div>
     </div>
    </div>
  <% end %>
<% end %>

app/views/searchs/all_search.html.erb
<!--検索結果-->

<% if @model == 'user'%>
  <% if @records != nil %>
     <h3 class="text-center m-3">ユーザー検索結果 "<%= @content %>"</h3>
     <% @records.each do |user| %>
     <div class="card mb-5 w-75  mx-auto shadow-lg">
       <p class="card-text ml-5 mt-2 link-color">
         <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class:"mt-3 mr-3 rounded-circle" %>
           by. <%= user.name %>
         <% end %>
       </p>
       <p class="introduction ml-5"><%= user.introduction %></p>
     </div>
   <% end %>
 <% end %>

 <% else @model == 'recipes' %>
   <h3 class="text-center m-3">レシピ検索結果 "<%= @content %>"</h3>
   <% @records.each do |recipe| %>
   <div class="card mb-5 w-75  mx-auto shadow-lg">
     <div class="row">
       <div class="col-lg-5-md-6-sm-6">
         <div class="img-container"><%= attachment_image_tag recipe, :image, :fill, 300, 300, fallback: "pngtree.jpg", size:'300x300' %></div>
       </div>
       <div class="col-lg-7-md-6-sm-6">
         <div class="card-body">
           <p class="card-text ml-5">
             <%= attachment_image_tag recipe.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class:"mt-3 mr-3 rounded-circle" %>
             by. <%= recipe.user.name %>
           </p>
           <h5 class="card-title ml-5">料理名：<%= link_to recipe_path(recipe.id), class:"link-color" do %>
               <%= recipe.title %>
             <% end %>
           </h5>
           <div class="catchcopy ml-5"><%= recipe.catchcopy %></div>
         </div>
      </div>
    </div>
   </div>
  <% end %>
<% end %>